version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.14.2
    restart: always
    volumes:
      - ./data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: 1qT8L8DMh92KUw==
      TZ: Asia/Shanghai
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - devops

  kibana:
    image: kibana:7.14.2
    restart: always
    volumes:
      - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      elasticsearch.hosts: http://elasticsearch:9200
      TZ: Asia/Shanghai
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - devops


  filebeat:
    image: elastic/filebeat:7.14.2
    restart: always
    volumes:
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /data/logs/:/var/log
    environment:
      elasticsearch.hosts: http://elasticsearch:9200
      TZ: Asia/Shanghai
    depends_on:
      - elasticsearch
    networks:
      - devops

networks:
  devops:
    external: true
